code/css/popup.css, code/js/popup.js, code/popup.html
https://github.com/OpenGenus/quark/issues/1
**Changes:**
Added a list of 10 popular tags to choose from, on start of homepage,
so that searching or learning further becomes easier.
On clicking a tag, search results for that particular tag is displayed.
Signed-off-by: nj2237 <nniranjhana@gmail.com>
=> code: add popular tags on homepage

code/js/popup.js
#10 
**Changes:**
All the README.md files which were coming in search results are now not displayed.
Also those folders which contain only these files are also not displayed.
=> README files removed

code/js/popup.js, code/popup.html
#7 
**Changes:**
After every search query, the total number of results found will be displayed.
=> Number of searches displayed

code/js/popup.js
**Changes:**
There was an unnecessary console.log() line which will be removed by this patch.
=> Removed unnecessary console log

code/css/popup.css
Fixes #50 
**Changes:**
Footer is fixed now. It appears at page bottom without depending on page content length.
=> Footer fixed

.github/ISSUE_TEMPLATE.md
Fixes #74 
**Changes:**
More information while opening a new issue can be provided now.
=> ISSUE_TEMPLATE updated

code/css/popup.css, code/js/popup.js
**Fixes issue:** #64 
**Changes:**
- Sorting by Date-Time/Area/Language added
- Searching by Algo/Date-Time/Area/Language added
A demo of this PR:
=> Organised Favourites Added

code/css/popup.css, code/popup.html
**Fixes issue:** https://github.com/OpenGenus/quark/issues/92
**Changes:** Fixed Footer and Extra Spacing in body
=> Fixed Footer and Extra Spacing in body

code/js/popup.js
**Fixes issue:** N/A
**Changes:**
In my previous merge, https://github.com/OpenGenus/quark/pull/79
There was a small error of adding the main Fav Header Row along with all rows while searching.
Rectified the same in this PR.
=> One Error in Organised Favourites resolved

code/js/popup.js
**Fixes issue:** https://github.com/OpenGenus/quark/issues/94
**Changes:** New Button added to clear all favorites in one go.
**Demo:**
=> Clear Favourites Button Added

code/background.js, code/contentScript.js, code/js/popup.js, code/manifest.json
Fixes #30 
**Changes:**
- A content script is added that would run in the context of web pages.
- If user has quark extension added then while browsing through any web page if he encounters any algorithm name then while hovering on it 'Search in quark' tooltip would appear, clicking on which quark homepage would open.
=> Quick Search implemented

code/js/popup.js
Added Promises in popup.js to resolve the issue of
Favorites tab being populated twice on double-clicking.
Signed-off-by: nj2237 <nniranjhana@gmail.com>
#83
=> code: Fixed bug on Favorites tab

code/css/popup.css, code/js/popup.js, code/popup.html
#110 
**Changes:**
A Scroll to Top button has been added which pops up at the bottom right of the page after the user has scrolled down by a sufficient amount.
On clicking the button, the user is redirected to the top of the page.
=> Scroll to Top feature added

code/js/popup.js, code/popup.html
#90 
**Changes:**
Missing lines of code are added.
Along with the mentioned errors in #90, this error was also found (the unwanted blank area in between).
This has also been rectified.
=> Errors due to Favorites removed

code/css/popup.css, code/js/popup.js
#66 
**Changes:**
A clear button is added in the search bar which gets activated as soon as user changes the contents of search bar.
=> Clear button in search bar added

code/popup.html
**Changes:**
Remove unnecessary tabs to better follow the coding convention for html files.
=> Remove unnecessary tabs in popup.html

code/js/popup.js
Fixes #5 
**Changes:**
On searching for any particular algorithm type, all the algorithm matching the search query are displayed.
Eg. While searching for Bubble Sort only those algorithms will be shown and not all sorting algorithms present.
=> Filtered search results

code/background.js, code/contentScript.js, code/css/sites.css, code/js/popup.js, code/js/sites.js, code/manifest.json, code/popup.html, code/sites.html, code/sitesScript.js
**Fixes issue:** https://github.com/OpenGenus/quark/issues/122
**Changes:**
- Background scripts added to quark to track other websites activity
- `Sites` button added to open a new page for this feature
Kindly Review this PR and suggest enhancement if required.
=> Time spent on various sites feature

code/js/sites.js, code/sites.html
=> Added percentage of time spent to sites.html

code/background-save.js, code/content-frame.js, code/content.js, code/manifest.json, code/pageloader.js
**Changes:**
This pull request adds a new feature of saving a page.
=> save page feature

code/js/sites.js, code/popup.html
**Changes:**
Added sorting feature on four columns in the Activity table in sites.html webpage.
=> Added sorting feature in Activity table

code/content.js, code/js/popup.js, code/saved.html, code/saved.js
=> Saving pages

code/saved.html, code/saved.js
Fixing small bug, where table was added to each page you are browsing, whenever it should be added only in saved.html in extension.
=> fix for saved pages feature

code/js/popup.js, code/popup.html
This PR is made for issue #31 [Add a Search button](https://github.com/OpenGenus/quark/issues/31)
**Changes:**
A button is added next to the search box, which when clicked, will show the results of the search.
=> added search button

code/saved.js
**Changes:**
Now we can also download already saved pages as an HTML file.
=> added Download feature for already saved pages
